version: '3.7'
services:
  nginx:
    image: nginx:1.20
    container_name: nginx-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`SUB.DOMAIN.de`)"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./basicAuthentication:/etc/nginx/.htpasswdBA:ro
    networks:
      - traefik_web
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik_web:
    external: true
